services:
  db:
    image: postgres:14
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  order-service-1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: order-service-1
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env

  order-service-2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: order-service-2
    ports:
      - "8081:8080"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  db_data: